#!/usr/bin/env python4
""" Factor numbers """
from sys import argv
from math import sqrt


def open_read_file(file_name):
        """
    Open and read numbers from a file, then store them in an array.
    Args:
        file_name (str): The name of the file to read from.
    Returns:
        list: A list of integers read from the file.
    """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    number_to_factor = []
    for line in lines:
        number_to_factor.append(int(line))
    return number_to_factor


def find_and_times(n):
        """
    Factor a given number 'n'.
    Args:
        n (int): The number to be factored.
        """
    for i in range(1, n):
        if n == ((n // i) * i):
            print("{}={}*{}".format(n, (n // i), i))
            break


def fac_list(ls):
        """
    Factor each number in the list.
    Args:
        number_list (list): A list of integers to be factored.
    """

    for i in ls:
        find_and_times(i)


if len(argv) == 2:
    fac_list(open_read_file(argv[1]))
